TRANSLATIONS = {
    'fr': {
        'app.name':'Buvette Manager','nav.operations':'Opérations','nav.management':'Gestion','nav.finance':'Finance','nav.admin':'Administration','nav.dashboard':'Tableau de bord','nav.clients':'Clients','nav.breakfast':'Petit déjeuner','nav.lunch':'Déjeuner','nav.payments':'Paiements','nav.products':'Produits','nav.menus':'Menus','nav.suppliers':'Fournisseurs','nav.expenses':'Dépenses','nav.ledger':'Grand livre','nav.reports':'Rapports','nav.users':'Utilisateurs','nav.settings':'Paramètres','nav.logs':'Journaux',
        'button.save':'Enregistrer','button.edit':'Modifier','button.delete':'Supprimer','button.archive':'Archiver','button.restore':'Restaurer','button.confirm':'Confirmer','button.cancel':'Annuler','button.back':'Retour','button.search':'Rechercher','button.logout':'Déconnexion','button.copy_previous_week':'Copier la semaine précédente','button.clear':'Effacer','button.backspace':'Retour arrière','button.add_plate':'Ajouter un plat','placeholder.select_plate':'Sélectionner un plat','placeholder.select_variant':'Sélectionner une taille','button.deactivate':'Désactiver','button.add':'Ajouter un plat',
        'weekday.monday':'Lundi','weekday.tuesday':'Mardi','weekday.wednesday':'Mercredi','weekday.thursday':'Jeudi','weekday.friday':'Vendredi','weekday.saturday':'Samedi','weekday.sunday':'Dimanche',
        'field.client':'Client','field.amount':'Montant','field.price':'Prix','field.active':'Actif','field.week':'Semaine','field.week_start':'Début de semaine','field.label':'Libellé','field.name':'Nom','field.description':'Description','field.variant':'Variante','field.employee_number':'Matricule','field.notes':'Notes','field.date':'Date','field.user':'Utilisateur','field.action':'Action','field.entity':'Entité','field.severity':'Gravité','field.password':'Mot de passe administrateur','field.debit':'Débit','field.credit':'Crédit','field.running_balance':'Solde courant','field.type':'Type',
        'dashboard.title':'Tableau de bord','dashboard.breakfast_revenue':'Recettes petit déjeuner du jour','dashboard.lunch_revenue':'Recettes déjeuner du jour','dashboard.payments_today':'Paiements clients du jour','dashboard.supplier_expenses_today':'Dépenses fournisseurs du jour','dashboard.outstanding_debt':'Impayés clients','dashboard.over_limit':'Clients au-dessus du plafond','dashboard.no_debt':'Aucun impayé client.','dashboard.avg_breakfast':'Moyenne petit déjeuner / jour','dashboard.avg_lunch':'Moyenne déjeuner / jour','dashboard.avg_payments':'Moyenne paiements / jour','dashboard.avg_expenses':'Moyenne dépenses / jour','dashboard.avg_period':'Moyenne calculée sur les 30 derniers jours.',
        'breakfast.title':'Petit déjeuner','breakfast.order':'Commande petit déjeuner','breakfast.products':'Produits','breakfast.confirm':'Confirmer le petit déjeuner','flash.breakfast_charged':'Petit déjeuner enregistré.','flash.product_saved':'Produit enregistré.',
        'payments.title':'Paiements','payments.cash':'Paiement client','payments.history':'Historique des paiements','flash.payment_saved':'Paiement enregistré.',
        'charges.title':'Dépenses fournisseurs','charges.history':'Historique des dépenses','flash.charge_saved':'Dépense fournisseur enregistrée.',
        'logs.title':'Journaux','logs.empty':'Aucun journal trouvé.',
        'lunch.title':'Déjeuner','lunch.menus.title':'Menus hebdomadaires','lunch.today_plates':'Plats du jour','lunch.no_menu_today':'Aucun menu actif n’est configuré pour aujourd’hui.','lunch.confirm_charge':'Confirmer le déjeuner','lunch.weekly_menu':'Menu hebdomadaire','lunch.daily_plates':'Plats journaliers','variant.small':'Petit','variant.big':'Grand','lunch.small':'Petit','lunch.big':'Grand','lunch.closed_today':'La buvette est fermée aujourd’hui.','lunch.closed':'Fermé','lunch.none_configured':'Aucun menu configuré','flash.lunch_charged':'Déjeuner enregistré.','flash.menu_saved':'Menu enregistré.','flash.menu_copied':'Menu copié.','flash.variant_saved':'Variante enregistrée.',
        'client.selector.title':'Sélectionner un client','client.selector.search':'Rechercher par nom ou matricule','client.recent':'Clients récents','client.balance':'Solde','client.debt_warning':'Attention dette',
        'error.required':'Ce champ est obligatoire.','error.generic':'Une erreur est survenue. Veuillez réessayer ou contacter l’administrateur.','error.permission_denied':'Accès refusé.','error.not_found':'Page introuvable.','error.server':'Une erreur interne est survenue.','error.invalid_amount':'Montant invalide.','error.delete_blocked':'Suppression bloquée par l’historique financier.',
        'status.yes':'Oui','status.no':'Non','currency.default':'DH'
    },
    'ar': {
        'app.name':'تسيير البوفيه','nav.operations':'العمليات','nav.management':'الإدارة اليومية','nav.finance':'المالية','nav.admin':'الإدارة','nav.dashboard':'لوحة التحكم','nav.clients':'الزبائن','nav.breakfast':'الفطور','nav.lunch':'الغداء','nav.payments':'الأداء','nav.products':'المنتجات','nav.menus':'القوائم','nav.suppliers':'الموردون','nav.expenses':'المصاريف','nav.ledger':'السجل','nav.reports':'التقارير','nav.users':'المستخدمون','nav.settings':'الإعدادات','nav.logs':'السجلات',
        'button.save':'حفظ','button.edit':'تعديل','button.delete':'حذف','button.archive':'أرشفة','button.restore':'استرجاع','button.confirm':'تأكيد','button.cancel':'إلغاء','button.back':'رجوع','button.search':'بحث','button.logout':'تسجيل الخروج','button.copy_previous_week':'نسخ الأسبوع السابق','button.clear':'مسح','button.backspace':'رجوع','button.add_plate':'إضافة طبق','placeholder.select_plate':'اختر الطبق','placeholder.select_variant':'اختر الحجم','button.deactivate':'تعطيل','button.add':'إضافة طبق',
        'weekday.monday':'الإثنين','weekday.tuesday':'الثلاثاء','weekday.wednesday':'الأربعاء','weekday.thursday':'الخميس','weekday.friday':'الجمعة','weekday.saturday':'السبت','weekday.sunday':'الأحد',
        'field.client':'الزبون','field.amount':'المبلغ','field.price':'الثمن','field.active':'نشط','field.week':'الأسبوع','field.week_start':'بداية الأسبوع','field.label':'التسمية','field.name':'الاسم','field.description':'الوصف','field.variant':'الحجم','field.employee_number':'رقم الموظف','field.notes':'ملاحظات','field.date':'التاريخ','field.user':'المستخدم','field.action':'العملية','field.entity':'الكيان','field.severity':'الخطورة','field.password':'كلمة مرور المدير','field.debit':'مدين','field.credit':'دائن','field.running_balance':'الرصيد الجاري','field.type':'النوع',
        'dashboard.title':'لوحة التحكم','dashboard.breakfast_revenue':'مداخيل الفطور اليوم','dashboard.lunch_revenue':'مداخيل الغداء اليوم','dashboard.payments_today':'أداءات الزبائن اليوم','dashboard.supplier_expenses_today':'مصاريف الموردين اليوم','dashboard.outstanding_debt':'ديون الزبائن','dashboard.over_limit':'زبائن تجاوزوا الحد','dashboard.no_debt':'لا توجد ديون على الزبائن.','dashboard.avg_breakfast':'متوسط طلبات الفطور / يوم','dashboard.avg_lunch':'متوسط طلبات الغداء / يوم','dashboard.avg_payments':'متوسط الأداءات / يوم','dashboard.avg_expenses':'متوسط المصاريف / يوم','dashboard.avg_period':'المتوسط محسوب على آخر 30 يوما.',
        'breakfast.title':'الفطور','breakfast.order':'طلب الفطور','breakfast.products':'المنتجات','breakfast.confirm':'تأكيد الفطور','flash.breakfast_charged':'تم تسجيل الفطور.','flash.product_saved':'تم حفظ المنتج.',
        'payments.title':'الأداء','payments.cash':'أداء الزبون','payments.history':'سجل الأداءات','flash.payment_saved':'تم حفظ الأداء.',
        'charges.title':'مصاريف الموردين','charges.history':'سجل المصاريف','flash.charge_saved':'تم تسجيل مصروف المورد.',
        'logs.title':'السجلات','logs.empty':'لا توجد سجلات.',
        'lunch.title':'الغداء','lunch.menus.title':'القوائم الأسبوعية','lunch.today_plates':'أطباق اليوم','lunch.no_menu_today':'لا توجد قائمة نشطة لهذا اليوم.','lunch.confirm_charge':'تأكيد الغداء','lunch.weekly_menu':'قائمة أسبوعية','lunch.daily_plates':'أطباق اليوم','variant.small':'صغير','variant.big':'كبير','lunch.small':'صغير','lunch.big':'كبير','lunch.closed_today':'البوفيت مغلق اليوم.','lunch.closed':'مغلق','lunch.none_configured':'لا توجد قائمة مهيأة','flash.lunch_charged':'تم تسجيل الغداء.','flash.menu_saved':'تم حفظ القائمة.','flash.menu_copied':'تم نسخ القائمة.','flash.variant_saved':'تم حفظ الحجم.',
        'client.selector.title':'اختيار الزبون','client.selector.search':'ابحث بالاسم أو رقم الموظف','client.recent':'آخر الزبائن','client.balance':'الرصيد','client.debt_warning':'تنبيه دين',
        'error.required':'هذا الحقل ضروري.','error.generic':'حدث خطأ. يرجى المحاولة مرة أخرى أو الاتصال بالمسؤول.','error.permission_denied':'غير مسموح.','error.not_found':'الصفحة غير موجودة.','error.server':'وقع خطأ داخلي.','error.invalid_amount':'مبلغ غير صالح.','error.delete_blocked':'الحذف ممنوع بسبب السجل المالي.',
        'status.yes':'نعم','status.no':'لا','currency.default':'DH'
    }
}
