TRANSLATIONS = {
    'fr': {
        'app.name':'Buvette Manager','nav.operations':'Opérations','nav.management':'Gestion','nav.finance':'Finance','nav.admin':'Administration','nav.dashboard':'Tableau de bord','nav.clients':'Clients','nav.breakfast':'Petit déjeuner','nav.lunch':'Déjeuner','nav.payments':'Paiements','nav.products':'Produits','nav.menus':'Menus','nav.suppliers':'Fournisseurs','nav.expenses':'Dépenses','nav.ledger':'Grand livre','nav.reports':'Rapports','nav.users':'Utilisateurs','nav.settings':'Paramètres','nav.logs':'Journaux',
        'button.save':'Enregistrer','button.edit':'Modifier','button.delete':'Supprimer','button.archive':'Archiver','button.restore':'Restaurer','button.confirm':'Confirmer','button.cancel':'Annuler','button.back':'Retour','button.search':'Rechercher','button.logout':'Déconnexion','button.copy_previous_week':'Copier la semaine précédente','button.clear':'Effacer','button.backspace':'Retour arrière','button.add_plate':'Ajouter un plat','placeholder.select_plate':'Sélectionner un plat','placeholder.select_variant':'Sélectionner une taille','button.deactivate':'Désactiver','button.add':'Ajouter un plat',
        'weekday.monday':'Lundi','weekday.tuesday':'Mardi','weekday.wednesday':'Mercredi','weekday.thursday':'Jeudi','weekday.friday':'Vendredi','weekday.saturday':'Samedi','weekday.sunday':'Dimanche',
        'field.client':'Client','field.amount':'Montant','field.price':'Prix','field.active':'Actif','field.week':'Semaine','field.week_start':'Début de semaine','field.label':'Libellé','field.name':'Nom','field.description':'Description','field.variant':'Variante','field.employee_number':'Matricule','field.notes':'Notes','field.date':'Date','field.user':'Utilisateur','field.action':'Action','field.entity':'Entité','field.severity':'Gravité','field.password':'Mot de passe administrateur','field.debit':'Débit','field.credit':'Crédit','field.running_balance':'Solde courant','field.type':'Type',
        'dashboard.title':'Tableau de bord','dashboard.breakfast_revenue':'Recettes petit déjeuner du jour','dashboard.lunch_revenue':'Recettes déjeuner du jour','dashboard.payments_today':'Paiements clients du jour','dashboard.supplier_expenses_today':'Dépenses fournisseurs du jour','dashboard.outstanding_debt':'Impayés clients','dashboard.over_limit':'Clients au-dessus du plafond','dashboard.no_debt':'Aucun impayé client.','dashboard.avg_breakfast':'Moyenne petit déjeuner / jour','dashboard.avg_lunch':'Moyenne déjeuner / jour','dashboard.avg_payments':'Moyenne paiements / jour','dashboard.avg_expenses':'Moyenne dépenses / jour','dashboard.avg_period':'Moyenne calculée sur les 30 derniers jours.',
        'breakfast.title':'Petit déjeuner','breakfast.order':'Commande petit déjeuner','breakfast.products':'Produits','breakfast.confirm':'Confirmer le petit déjeuner','flash.breakfast_charged':'Petit déjeuner enregistré.','flash.product_saved':'Produit enregistré.',
        'payments.title':'Paiements','payments.cash':'Paiement client','payments.history':'Historique des paiements','flash.payment_saved':'Paiement enregistré.',
        'charges.title':'Dépenses fournisseurs','charges.history':'Historique des dépenses','flash.charge_saved':'Dépense fournisseur enregistrée.',
        'logs.title':'Journaux','logs.empty':'Aucun journal trouvé.',
        'lunch.title':'Déjeuner','lunch.menus.title':'Menus hebdomadaires','lunch.today_plates':'Plats du jour','lunch.no_menu_today':'Aucun menu actif n’est configuré pour aujourd’hui.','lunch.confirm_charge':'Confirmer le déjeuner','lunch.weekly_menu':'Menu hebdomadaire','lunch.daily_plates':'Plats journaliers','variant.small':'Petit','variant.big':'Grand','lunch.small':'Petit','lunch.big':'Grand','lunch.closed_today':'La buvette est fermée aujourd’hui.','lunch.closed':'Fermé','lunch.none_configured':'Aucun menu configuré','flash.lunch_charged':'Déjeuner enregistré.','flash.menu_saved':'Menu enregistré.','flash.menu_copied':'Menu copié.','flash.variant_saved':'Variante enregistrée.',
        'client.selector.title':'Sélectionner un client','client.selector.search':'Rechercher par nom ou matricule','client.recent':'Clients récents','client.balance':'Solde','client.debt_warning':'Attention dette',
        'error.required':'Ce champ est obligatoire.','error.generic':'Une erreur est survenue. Veuillez réessayer ou contacter l’administrateur.','error.permission_denied':'Accès refusé.','error.not_found':'Page introuvable.','error.server':'Une erreur interne est survenue.','error.invalid_amount':'Montant invalide.','error.delete_blocked':'Suppression bloquée par l’historique financier.',
        'status.yes':'Oui','status.no':'Non','auth.login':'Connexion','auth.username':'Nom d’utilisateur','auth.password':'Mot de passe','auth.submit':'Se connecter','settings.title':'Paramètres','settings.identity':'Identité de l’organisation','settings.organization_name':'Nom de l’organisation','settings.short_name':'Nom court','settings.logo':'Logo','settings.logo_help':'Formats acceptés : PNG, JPG, JPEG, WEBP ou SVG sécurisé.','settings.primary_color':'Couleur principale','settings.secondary_color':'Couleur secondaire','settings.accent_color':'Couleur d’accent','settings.header_background_color':'Couleur de l’en-tête','settings.sidebar_background_color':'Couleur du menu latéral','settings.button_color':'Couleur des boutons','settings.login_background_color':'Couleur de fond de connexion','settings.footer_text':'Texte du pied de page','settings.currency':'Devise','settings.debt_warning_default':'Seuil d’alerte dette','settings.passwords':'Mots de passe','settings.administrator_password':'Mot de passe administrateur','settings.cashier_password':'Mot de passe caissier','settings.admin_links':'Administration des menus et produits','settings.flash.saved':'Paramètres enregistrés.','settings.error.organization_required':'Le nom de l’organisation est obligatoire.','settings.error.debt_negative':'Le seuil d’alerte dette ne peut pas être négatif.','settings.error.invalid_color':'La couleur doit être au format hexadécimal #RRGGBB.','settings.error.invalid_logo':'Le fichier logo doit être un PNG, JPG, JPEG, WEBP ou SVG sécurisé.','settings.error.logo_write_failed':'Impossible d’enregistrer le logo. Veuillez réessayer.','settings.error.validation':'Veuillez corriger les champs indiqués.','ledger.export_all':'Exporter tout','ledger.export_filtered':'Exporter la période filtrée',
        'auth.login':'تسجيل الدخول','auth.username':'اسم المستخدم','auth.password':'كلمة المرور','auth.submit':'دخول','settings.title':'الإعدادات','settings.identity':'هوية المؤسسة','settings.organization_name':'اسم المؤسسة','settings.short_name':'الاسم المختصر','settings.logo':'الشعار','settings.logo_help':'الصيغ المقبولة: PNG أو JPG أو JPEG أو WEBP أو SVG آمن.','settings.primary_color':'اللون الرئيسي','settings.secondary_color':'اللون الثانوي','settings.accent_color':'لون التمييز','settings.header_background_color':'لون الرأس','settings.sidebar_background_color':'لون القائمة الجانبية','settings.button_color':'لون الأزرار','settings.login_background_color':'لون خلفية تسجيل الدخول','settings.footer_text':'نص التذييل','settings.currency':'العملة','settings.debt_warning_default':'حد تنبيه الدين','settings.passwords':'كلمات المرور','settings.administrator_password':'كلمة مرور المدير','settings.cashier_password':'كلمة مرور أمين الصندوق','settings.admin_links':'إدارة القوائم والمنتجات','settings.flash.saved':'تم حفظ الإعدادات.','settings.error.organization_required':'اسم المؤسسة ضروري.','settings.error.debt_negative':'حد تنبيه الدين لا يمكن أن يكون سالبا.','settings.error.invalid_color':'يجب أن يكون اللون بصيغة #RRGGBB.','settings.error.invalid_logo':'يجب أن يكون الشعار PNG أو JPG أو JPEG أو WEBP أو SVG آمن.','settings.error.logo_write_failed':'تعذر حفظ الشعار. حاول مرة أخرى.','settings.error.validation':'يرجى تصحيح الحقول المشار إليها.','ledger.export_all':'تصدير الكل','ledger.export_filtered':'تصدير الفترة المحددة',
        'currency.default':'DH'
    },
    'ar': {
        'app.name':'تسيير البوفيه','nav.operations':'العمليات','nav.management':'الإدارة اليومية','nav.finance':'المالية','nav.admin':'الإدارة','nav.dashboard':'لوحة التحكم','nav.clients':'الزبائن','nav.breakfast':'الفطور','nav.lunch':'الغداء','nav.payments':'الأداء','nav.products':'المنتجات','nav.menus':'القوائم','nav.suppliers':'الموردون','nav.expenses':'المصاريف','nav.ledger':'السجل','nav.reports':'التقارير','nav.users':'المستخدمون','nav.settings':'الإعدادات','nav.logs':'السجلات',
        'button.save':'حفظ','button.edit':'تعديل','button.delete':'حذف','button.archive':'أرشفة','button.restore':'استرجاع','button.confirm':'تأكيد','button.cancel':'إلغاء','button.back':'رجوع','button.search':'بحث','button.logout':'تسجيل الخروج','button.copy_previous_week':'نسخ الأسبوع السابق','button.clear':'مسح','button.backspace':'رجوع','button.add_plate':'إضافة طبق','placeholder.select_plate':'اختر الطبق','placeholder.select_variant':'اختر الحجم','button.deactivate':'تعطيل','button.add':'إضافة طبق',
        'weekday.monday':'الإثنين','weekday.tuesday':'الثلاثاء','weekday.wednesday':'الأربعاء','weekday.thursday':'الخميس','weekday.friday':'الجمعة','weekday.saturday':'السبت','weekday.sunday':'الأحد',
        'field.client':'الزبون','field.amount':'المبلغ','field.price':'الثمن','field.active':'نشط','field.week':'الأسبوع','field.week_start':'بداية الأسبوع','field.label':'التسمية','field.name':'الاسم','field.description':'الوصف','field.variant':'الحجم','field.employee_number':'رقم الموظف','field.notes':'ملاحظات','field.date':'التاريخ','field.user':'المستخدم','field.action':'العملية','field.entity':'الكيان','field.severity':'الخطورة','field.password':'كلمة مرور المدير','field.debit':'مدين','field.credit':'دائن','field.running_balance':'الرصيد الجاري','field.type':'النوع',
        'dashboard.title':'لوحة التحكم','dashboard.breakfast_revenue':'مداخيل الفطور اليوم','dashboard.lunch_revenue':'مداخيل الغداء اليوم','dashboard.payments_today':'أداءات الزبائن اليوم','dashboard.supplier_expenses_today':'مصاريف الموردين اليوم','dashboard.outstanding_debt':'ديون الزبائن','dashboard.over_limit':'زبائن تجاوزوا الحد','dashboard.no_debt':'لا توجد ديون على الزبائن.','dashboard.avg_breakfast':'متوسط طلبات الفطور / يوم','dashboard.avg_lunch':'متوسط طلبات الغداء / يوم','dashboard.avg_payments':'متوسط الأداءات / يوم','dashboard.avg_expenses':'متوسط المصاريف / يوم','dashboard.avg_period':'المتوسط محسوب على آخر 30 يوما.',
        'breakfast.title':'الفطور','breakfast.order':'طلب الفطور','breakfast.products':'المنتجات','breakfast.confirm':'تأكيد الفطور','flash.breakfast_charged':'تم تسجيل الفطور.','flash.product_saved':'تم حفظ المنتج.',
        'payments.title':'الأداء','payments.cash':'أداء الزبون','payments.history':'سجل الأداءات','flash.payment_saved':'تم حفظ الأداء.',
        'charges.title':'مصاريف الموردين','charges.history':'سجل المصاريف','flash.charge_saved':'تم تسجيل مصروف المورد.',
        'logs.title':'السجلات','logs.empty':'لا توجد سجلات.',
        'lunch.title':'الغداء','lunch.menus.title':'القوائم الأسبوعية','lunch.today_plates':'أطباق اليوم','lunch.no_menu_today':'لا توجد قائمة نشطة لهذا اليوم.','lunch.confirm_charge':'تأكيد الغداء','lunch.weekly_menu':'قائمة أسبوعية','lunch.daily_plates':'أطباق اليوم','variant.small':'صغير','variant.big':'كبير','lunch.small':'صغير','lunch.big':'كبير','lunch.closed_today':'البوفيت مغلق اليوم.','lunch.closed':'مغلق','lunch.none_configured':'لا توجد قائمة مهيأة','flash.lunch_charged':'تم تسجيل الغداء.','flash.menu_saved':'تم حفظ القائمة.','flash.menu_copied':'تم نسخ القائمة.','flash.variant_saved':'تم حفظ الحجم.',
        'client.selector.title':'اختيار الزبون','client.selector.search':'ابحث بالاسم أو رقم الموظف','client.recent':'آخر الزبائن','client.balance':'الرصيد','client.debt_warning':'تنبيه دين',
        'error.required':'هذا الحقل ضروري.','error.generic':'حدث خطأ. يرجى المحاولة مرة أخرى أو الاتصال بالمسؤول.','error.permission_denied':'غير مسموح.','error.not_found':'الصفحة غير موجودة.','error.server':'وقع خطأ داخلي.','error.invalid_amount':'مبلغ غير صالح.','error.delete_blocked':'الحذف ممنوع بسبب السجل المالي.',
        'status.yes':'نعم','status.no':'لا','currency.default':'DH'
    }
}

TRANSLATIONS['fr'].update({
'auth.login':'Connexion','auth.username':'Nom d’utilisateur','auth.password':'Mot de passe','auth.submit':'Se connecter','settings.title':'Paramètres','settings.identity':'Identité de l’organisation','settings.organization_name':'Nom de l’organisation','settings.short_name':'Nom court','settings.logo':'Logo','settings.logo_help':'Formats acceptés : PNG, JPG, JPEG, WEBP ou SVG sécurisé.','settings.colors':'Couleurs','settings.primary_color':'Couleur principale','settings.secondary_color':'Couleur secondaire','settings.accent_color':'Couleur d’accent','settings.header_background_color':'Couleur de l’en-tête','settings.sidebar_background_color':'Couleur du menu latéral','settings.button_color':'Couleur des boutons','settings.login_background_color':'Couleur de fond de connexion','settings.footer_text':'Texte du pied de page','settings.currency':'Devise','settings.debt_warning_default':'Seuil d’alerte dette','settings.passwords':'Mots de passe','settings.administrator_password':'Mot de passe administrateur','settings.cashier_password':'Mot de passe caissier','settings.admin_links':'Administration des menus et produits','settings.flash.saved':'Paramètres enregistrés.','settings.error.organization_required':'Le nom de l’organisation est obligatoire.','settings.error.debt_negative':'Le seuil d’alerte dette ne peut pas être négatif.','settings.error.invalid_color':'La couleur doit être au format hexadécimal #RRGGBB.','settings.error.invalid_logo':'Le fichier logo doit être un PNG, JPG, JPEG, WEBP ou SVG sécurisé.','settings.error.logo_write_failed':'Impossible d’enregistrer le logo. Veuillez réessayer.','settings.error.validation':'Veuillez corriger les champs indiqués.','ledger.export_all':'Exporter tout','ledger.export_filtered':'Exporter la période filtrée'
})
TRANSLATIONS['ar'].update({
'auth.login':'تسجيل الدخول','auth.username':'اسم المستخدم','auth.password':'كلمة المرور','auth.submit':'دخول','settings.title':'الإعدادات','settings.identity':'هوية المؤسسة','settings.organization_name':'اسم المؤسسة','settings.short_name':'الاسم المختصر','settings.logo':'الشعار','settings.logo_help':'الصيغ المقبولة: PNG أو JPG أو JPEG أو WEBP أو SVG آمن.','settings.colors':'الألوان','settings.primary_color':'اللون الرئيسي','settings.secondary_color':'اللون الثانوي','settings.accent_color':'لون التمييز','settings.header_background_color':'لون الرأس','settings.sidebar_background_color':'لون القائمة الجانبية','settings.button_color':'لون الأزرار','settings.login_background_color':'لون خلفية تسجيل الدخول','settings.footer_text':'نص التذييل','settings.currency':'العملة','settings.debt_warning_default':'حد تنبيه الدين','settings.passwords':'كلمات المرور','settings.administrator_password':'كلمة مرور المدير','settings.cashier_password':'كلمة مرور أمين الصندوق','settings.admin_links':'إدارة القوائم والمنتجات','settings.flash.saved':'تم حفظ الإعدادات.','settings.error.organization_required':'اسم المؤسسة ضروري.','settings.error.debt_negative':'حد تنبيه الدين لا يمكن أن يكون سالبا.','settings.error.invalid_color':'يجب أن يكون اللون بصيغة #RRGGBB.','settings.error.invalid_logo':'يجب أن يكون الشعار PNG أو JPG أو JPEG أو WEBP أو SVG آمن.','settings.error.logo_write_failed':'تعذر حفظ الشعار. حاول مرة أخرى.','settings.error.validation':'يرجى تصحيح الحقول المشار إليها.','ledger.export_all':'تصدير الكل','ledger.export_filtered':'تصدير الفترة المحددة'
})

TRANSLATIONS['fr'].update({
    'lunch.menus.help':'Créez une semaine, puis ouvrez un jour pour gérer ses plats et ses tarifs.',
    'lunch.menus.new_week':'Nouvelle semaine',
    'lunch.menus.new_week_help':'Commencez un nouveau menu ou préparez la semaine à venir.',
    'lunch.menus.label_example':'Ex. Menu du 17 août',
    'lunch.menus.create':'Créer la semaine',
    'lunch.menus.days':'jours',
    'lunch.menus.plates':'plats',
    'lunch.menus.week_hint':'Ouvrez un jour ci-dessous pour ajouter ou modifier ses plats.',
    'lunch.menus.plate_name':'Nom du plat',
    'lunch.menus.optional':'Facultatif',
    'lunch.menus.status':'Statut',
    'lunch.menus.variants':'Variantes et prix',
    'lunch.menus.no_weeks':'Aucune semaine créée. Utilisez le formulaire ci-dessus pour commencer.'
})
TRANSLATIONS['ar'].update({
    'lunch.menus.help':'أنشئ أسبوعا ثم افتح يوما لإدارة أطباقه وأسعاره.',
    'lunch.menus.new_week':'أسبوع جديد',
    'lunch.menus.new_week_help':'ابدأ قائمة جديدة أو حضّر الأسبوع القادم.',
    'lunch.menus.label_example':'مثال: قائمة 17 غشت',
    'lunch.menus.create':'إنشاء الأسبوع',
    'lunch.menus.days':'أيام',
    'lunch.menus.plates':'أطباق',
    'lunch.menus.week_hint':'افتح يوما أدناه لإضافة أطباقه أو تعديلها.',
    'lunch.menus.plate_name':'اسم الطبق',
    'lunch.menus.optional':'اختياري',
    'lunch.menus.status':'الحالة',
    'lunch.menus.variants':'الأحجام والأسعار',
    'lunch.menus.no_weeks':'لم يتم إنشاء أي أسبوع. استخدم النموذج أعلاه للبدء.'
})
TRANSLATIONS['fr'].update({
'breakfast.edit_product':'Modifier le produit','flash.product_deleted':'Produit supprimé.','flash.product_duplicate':'Un produit actif porte déjà ce nom.','product_type.breakfast':'Petit déjeuner','product_type.drink':'Boisson','product_type.lunch_extra':'Extra déjeuner','charges.buvette_expenses':'Dépenses buvette','charges.recent':'Dépenses récentes','ledger.global':'Grand livre global','ledger.client':'Grand livre client','ledger.income':'Revenu','ledger.expense':'Dépense','ledger.net_total':'Résultat net','ledger.all':'Tous','ledger.source':'Source','dashboard.period':'Période','period.daily':'Aujourd’hui','period.weekly':'Cette semaine','period.monthly':'Ce mois','period.3months':'3 derniers mois','dashboard.breakfast_orders_today':'Commandes petit déjeuner du jour','dashboard.lunch_orders_today':'Commandes déjeuner du jour','dashboard.expenses_created_today':'Dépenses buvette créées aujourd’hui','dashboard.quick_actions':'Actions rapides','lunch.drinks':'Boissons','lunch.add_drink':'Ajouter une boisson','lunch.no_variant':'Aucune variante active pour ce plat.','settings.logo_label':'Logo','settings.organization':'Organisation'
})
TRANSLATIONS['ar'].update({
'breakfast.edit_product':'تعديل المنتج','flash.product_deleted':'تم حذف المنتج.','flash.product_duplicate':'يوجد منتج نشط بنفس الاسم.','product_type.breakfast':'الفطور','product_type.drink':'مشروب','product_type.lunch_extra':'إضافة الغداء','charges.buvette_expenses':'مصاريف البوفيه','charges.recent':'المصاريف الأخيرة','ledger.global':'السجل العام','ledger.client':'سجل الزبون','ledger.income':'دخل','ledger.expense':'مصروف','ledger.net_total':'الصافي','ledger.all':'الكل','ledger.source':'المصدر','dashboard.period':'الفترة','period.daily':'اليوم','period.weekly':'هذا الأسبوع','period.monthly':'هذا الشهر','period.3months':'آخر 3 أشهر','dashboard.breakfast_orders_today':'عدد طلبات الفطور اليوم','dashboard.lunch_orders_today':'عدد طلبات الغداء اليوم','dashboard.expenses_created_today':'مصاريف البوفيه المسجلة اليوم','dashboard.quick_actions':'إجراءات سريعة','lunch.drinks':'المشروبات','lunch.add_drink':'إضافة مشروب','lunch.no_variant':'لا يوجد حجم نشط لهذا الطبق.','settings.logo_label':'الشعار','settings.organization':'المؤسسة'
})
